# Generated by Django 2.1 on 2019-08-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_auto_20190829_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='fechadeentrega',
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='fechadedevolucion',
            field=models.DateField(null=True, verbose_name='Fecha de devolución'),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='fechadecompra',
            field=models.DateField(default=None, verbose_name='Fecha de compra'),
            preserve_default=False,
        ),
    ]
